name: Build Docker Image

on:
  pull_request:
    branches:
      - v2.0  # Optional: Run the workflow on PRs target

jobs:
  build-and-push:
    runs-on: image-builder

    permissions:
      contents: read
      packages: none  # Required to push to GitHub Container Registry

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./dockerfiles/debian.dockerfile
          platforms: linux/arm64,linux/amd64
          push: false
          tags: ghcr.io/${{ github.repository }}:2.0